sonar.projectKey=webapp
sonar.projectName=webapp
sonar.sources=src/main
sonar.tests=src/test

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.codeCoveragePlugin=jacoco

sonar.exclusions=src/main/webapp/WEB-INF/web.xml
sonar.cpd.exclusions=**/*.xml,Dockerfile,pipeline/settings.xml