# Required metadata
sonar.projectKey=webapp
sonar.projectName=webapp

# Paths to source directories
sonar.sources=src/main
sonar.tests=src/test

# Comma-separated paths to directories containing test resources
sonar.exclusions=

# add coverage plugin
sonar.java.coveragePlugin=jacoco

# report paths
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml

# Language of the source code
sonar.language=java